project:
  type: website
  output-dir: _site
  resources:
    - projects/projects.json
    - posts/posts.json
    - assets/js/render-cards.js
    - styles.css

website:
  title: "LCPallares"
  favicon: /assets/images/logo.svg
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    logo: assets/images/logo.svg
    left:
      - href: index.qmd
        text: Inicio
      - href: projects/
        text: Proyectos
      - href: posts/
        text: Blog
      - href: about.qmd
        text: Acerca de
    right:
      - icon: github
        href: https://github.com/lcpallares
      - icon: linkedin
        href: https://linkedin.com/in/lcpallares

  sidebar:
    - title: "Categorías"
      contents:
        - href: posts/tag-estadistica.qmd
          text: Estadística
        - href: posts/tag-data-apps.qmd
          text: Data Apps
        - href: posts/tag-visualizacion.qmd
          text: Visualización

  page-footer:
    border: true
    left: |
      Powered by [{{< iconify simple-icons:quarto >}} Quarto](https://quarto.org).
    center: |
      &copy; 2025 LCPallares.
    right: |
      License: [CC BY NC SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0).


format:
  html:
    theme: 
      - cosmo
    css: styles.css
    toc: true