{
  "hash": "96c31576fb30bdf8c1cfd05ea0e21a9a",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Inteligencia Analítica en Construcción\"\nsubtitle: \"EVM · Presupuesto APU · Modelos Predictivos · Power BI + Python Dash\"\ndescription: |\n  Dashboard de control de proyectos para una constructora colombiana con portafolio \n  de $50.8B COP. Análisis EVM, predicción de costos al cierre (CRISP-DM), \n  scorecard de contratistas y visualización en Power BI y Python Dash.\nauthor: \"LCPallares\"\ndate: \"2024-09-30\"\ndate-format: \"MMMM YYYY\"\nlang: es\n\ncategories:\n  - Power BI\n  - Python\n  - Dash\n  - EVM\n  - Construcción\n  - CRISP-DM\n  - Analítica de Negocios\n\nimage: \"img/preview.png\"   # ← reemplaza con tu captura del dashboard\n\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    toc-title: \"Contenido\"\n    toc-location: left\n    number-sections: false\n    code-fold: true\n    code-summary: \"Ver código\"\n    code-tools: true\n    highlight-style: github\n    theme: cosmo\n    css: styles.css        # opcional — si tienes estilos propios del sitio\n    fig-align: center\n    fig-cap-location: bottom\n    df-print: paged\n    embed-resources: true\n\nexecute:\n  echo: true\n  warning: false\n  message: false\n  eval: true               # ← cambia a false si no quieres re-ejecutar al renderizar\n\n---\n\n\n## Resumen del proyecto\n\nEste proyecto simula el sistema de **inteligencia analítica** de *Constructora Andina Proyectos S.A.S.*, empresa colombiana con un portafolio activo de 8 proyectos de obra civil y edificación.\n\nEl objetivo es demostrar cómo las técnicas de análisis de datos — combinadas con conocimiento del sector construcción colombiano — permiten tomar mejores decisiones en la gestión de proyectos.\n\n::: {.callout-note appearance=\"minimal\"}\n**Datos sintéticos** generados con distribuciones realistas según estándares INVIAS, Camacol y Contraloría General de la República. Los perfiles de CPI/SPI respetan los rangos típicos de obra civil colombiana (0.85–1.05).\n:::\n\n---\n\n## Contexto de negocio\n\n### ¿Por qué EVM en construcción colombiana?\n\nEn Colombia, la mayoría de proyectos de obra pública se ejecutan bajo contratos de **precio global fijo** o **precios unitarios**, lo que hace que el control de costos sea crítico. El **Earned Value Management (EVM)** es el estándar internacional (PMBOK, NTC-ISO 21500) para medir simultáneamente desempeño en costo y cronograma.\n\n| Indicador | Portafolio (Sep 2024) | Interpretación |\n|---|---|---|\n| **CPI** | 0\\.923 | Por cada $1 gastado se produce $0\\.92 de valor |\n| **SPI** | 0\\.948 | Avanzando al 94\\.8% de la velocidad planeada |\n| **EAC** | $55\\.141 B COP | Proyección de costo final |\n| **Sobrecosto** | $4\\.261 B COP | Desviación estimada al cierre |\n\n: KPIs ejecutivos del portafolio — Corte septiembre 2024 {.striped}\n\n### Portafolio de proyectos\n\n::: {#tbl-proyectos .cell tbl-cap='8 proyectos activos — estado al corte Sep 2024' execution_count=2}\n``` {.python .cell-code}\ndf_tbl = ultimo[[\"id_proyecto\",\"nombre\",\"tipo_proyecto\",\"CPI\",\"SPI\",\"avance_fisico_pct\",\"presupuesto_oficial\"]].copy()\ndf_tbl[\"EAC\"] = df_tbl[\"presupuesto_oficial\"] / df_tbl[\"CPI\"]\ndf_tbl[\"Desv %\"] = (df_tbl[\"EAC\"] - df_tbl[\"presupuesto_oficial\"]) / df_tbl[\"presupuesto_oficial\"] * 100\ndf_tbl[\"Semáforo\"] = df_tbl[\"CPI\"].apply(\n    lambda v: \"🔴 CRÍTICO\" if v < 0.85 else (\"🟡 ATENCIÓN\" if v < 0.95 else \"🟢 NORMAL\")\n)\n\ndisplay = df_tbl[[\"nombre\",\"tipo_proyecto\",\"presupuesto_oficial\",\"CPI\",\"SPI\",\"avance_fisico_pct\",\"Desv %\",\"Semáforo\"]].copy()\ndisplay.columns = [\"Proyecto\",\"Tipo\",\"BAC (COP)\",\"CPI\",\"SPI\",\"Avance %\",\"Desv %\",\"Estado\"]\ndisplay[\"BAC (COP)\"] = display[\"BAC (COP)\"].apply(lambda v: f\"${v/1e9:.3f} B\")\ndisplay[\"CPI\"] = display[\"CPI\"].apply(lambda v: f\"{v:.3f}\")\ndisplay[\"SPI\"] = display[\"SPI\"].apply(lambda v: f\"{v:.3f}\")\ndisplay[\"Avance %\"] = display[\"Avance %\"].apply(lambda v: f\"{v:.0f}%\")\ndisplay[\"Desv %\"] = display[\"Desv %\"].apply(lambda v: f\"+{v:.1f}%\")\ndisplay.set_index(\"Proyecto\", inplace=True)\ndisplay\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Tipo</th>\n      <th>BAC (COP)</th>\n      <th>CPI</th>\n      <th>SPI</th>\n      <th>Avance %</th>\n      <th>Desv %</th>\n      <th>Estado</th>\n    </tr>\n    <tr>\n      <th>Proyecto</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Via Terciaria Km 12 - Km 28</th>\n      <td>Vias</td>\n      <td>$4.800 B</td>\n      <td>0.881</td>\n      <td>0.890</td>\n      <td>88%</td>\n      <td>+13.5%</td>\n      <td>🟡 ATENCIÓN</td>\n    </tr>\n    <tr>\n      <th>Edificio Oficinas Zona Rosa 8 pisos</th>\n      <td>Edificacion</td>\n      <td>$12.500 B</td>\n      <td>0.963</td>\n      <td>0.969</td>\n      <td>89%</td>\n      <td>+3.9%</td>\n      <td>🟢 NORMAL</td>\n    </tr>\n    <tr>\n      <th>Puente Vehicular Rio Magdalena</th>\n      <td>Puentes</td>\n      <td>$8.200 B</td>\n      <td>0.850</td>\n      <td>0.951</td>\n      <td>61%</td>\n      <td>+17.7%</td>\n      <td>🔴 CRÍTICO</td>\n    </tr>\n    <tr>\n      <th>Parque Industrial Zona Franca</th>\n      <td>Urbanizacion</td>\n      <td>$6.400 B</td>\n      <td>0.948</td>\n      <td>0.956</td>\n      <td>29%</td>\n      <td>+5.5%</td>\n      <td>🟡 ATENCIÓN</td>\n    </tr>\n    <tr>\n      <th>Colector Aguas Residuales Zona Norte</th>\n      <td>Redes</td>\n      <td>$3.100 B</td>\n      <td>0.877</td>\n      <td>0.944</td>\n      <td>67%</td>\n      <td>+14.0%</td>\n      <td>🟡 ATENCIÓN</td>\n    </tr>\n    <tr>\n      <th>Ampliacion Hospital Regional</th>\n      <td>Edificacion</td>\n      <td>$5.600 B</td>\n      <td>0.993</td>\n      <td>0.992</td>\n      <td>29%</td>\n      <td>+0.7%</td>\n      <td>🟢 NORMAL</td>\n    </tr>\n    <tr>\n      <th>Estudio Geotecnico Variante Norte</th>\n      <td>Consultoria</td>\n      <td>$0.480 B</td>\n      <td>0.978</td>\n      <td>0.972</td>\n      <td>55%</td>\n      <td>+2.2%</td>\n      <td>🟢 NORMAL</td>\n    </tr>\n    <tr>\n      <th>Urbanizacion Residencial 200 Casas</th>\n      <td>Urbanizacion</td>\n      <td>$9.800 B</td>\n      <td>0.938</td>\n      <td>0.937</td>\n      <td>60%</td>\n      <td>+6.6%</td>\n      <td>🟡 ATENCIÓN</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n---\n\n## Stack técnico\n\nEl proyecto integra dos capas de visualización complementarias:\n\n::: {.grid}\n\n::: {.g-col-6}\n### Power BI\n- Modelo estrella con 4 dimensiones y 5 tablas de hechos\n- Medidas DAX para CPI, SPI, EAC, alertas semafóricas\n- 5 páginas completas entregadas como medidas `HTML Content`\n- Cross-filtering nativo entre visualizaciones\n- Fuente Barlow Condensed (equivalente DIN) vía Google Fonts\n:::\n\n::: {.g-col-6}\n### Python Dash\n- App completa con navegación lateral de 5 páginas\n- Datos cargados directamente desde los CSV con `pandas`\n- Gráficas interactivas con `plotly` (curvas S, scatter, tablas)\n- Cross-filtering manual: click en barra → filtra scatter + tabla\n- ~1200 líneas, sin dependencias de BI propietario\n:::\n\n:::\n\n\n```{=html}\n<figure style=\"text-align:center; margin: 1.5rem 0;\">\n<svg viewBox=\"0 0 760 160\" xmlns=\"http://www.w3.org/2000/svg\"\n     style=\"width:100%; max-width:760px; font-family:'Barlow Condensed',sans-serif;\">\n  <defs>\n    <marker id=\"arr\" markerWidth=\"8\" markerHeight=\"8\" refX=\"6\" refY=\"3\" orient=\"auto\">\n      <path d=\"M0,0 L7,3 L0,6 Z\" fill=\"#8899aa\"/>\n    </marker>\n  </defs>\n\n  <!-- Nodo 1: script Python -->\n  <rect x=\"10\"  y=\"50\" width=\"170\" height=\"60\" rx=\"8\" fill=\"#0f1f3d\"/>\n  <text x=\"95\"  y=\"76\" text-anchor=\"middle\" font-size=\"11\" font-weight=\"700\" fill=\"white\">construccion_analitica.py</text>\n  <text x=\"95\"  y=\"93\" text-anchor=\"middle\" font-size=\"10\" fill=\"#c9a84c\">Python · pandas · numpy</text>\n\n  <!-- Flecha 1 → 2 -->\n  <line x1=\"180\" y1=\"80\" x2=\"228\" y2=\"80\" stroke=\"#8899aa\" stroke-width=\"2\" marker-end=\"url(#arr)\"/>\n  <text x=\"204\" y=\"73\" text-anchor=\"middle\" font-size=\"9\" fill=\"#8899aa\">genera</text>\n\n  <!-- Nodo 2: CSV -->\n  <rect x=\"230\" y=\"50\" width=\"150\" height=\"60\" rx=\"8\" fill=\"#c9a84c\"/>\n  <text x=\"305\" y=\"76\" text-anchor=\"middle\" font-size=\"11\" font-weight=\"700\" fill=\"white\">11 CSV</text>\n  <text x=\"305\" y=\"93\" text-anchor=\"middle\" font-size=\"10\" fill=\"white\">data_powerbi/</text>\n\n  <!-- Flecha 2 → Power BI -->\n  <line x1=\"380\" y1=\"68\" x2=\"448\" y2=\"38\" stroke=\"#8899aa\" stroke-width=\"2\" marker-end=\"url(#arr)\"/>\n  <text x=\"418\" y=\"45\" text-anchor=\"middle\" font-size=\"9\" fill=\"#8899aa\">importa</text>\n\n  <!-- Flecha 2 → Dash -->\n  <line x1=\"380\" y1=\"92\" x2=\"448\" y2=\"122\" stroke=\"#8899aa\" stroke-width=\"2\" marker-end=\"url(#arr)\"/>\n  <text x=\"418\" y=\"122\" text-anchor=\"middle\" font-size=\"9\" fill=\"#8899aa\">lee</text>\n\n  <!-- Nodo 3: Power BI -->\n  <rect x=\"450\" y=\"10\" width=\"150\" height=\"55\" rx=\"8\" fill=\"#117aca\"/>\n  <text x=\"525\" y=\"33\" text-anchor=\"middle\" font-size=\"11\" font-weight=\"700\" fill=\"white\">Power BI</text>\n  <text x=\"525\" y=\"50\" text-anchor=\"middle\" font-size=\"10\" fill=\"white\">Dashboard · DAX · HTML</text>\n\n  <!-- Nodo 4: Dash -->\n  <rect x=\"450\" y=\"95\" width=\"150\" height=\"55\" rx=\"8\" fill=\"#00b894\"/>\n  <text x=\"525\" y=\"118\" text-anchor=\"middle\" font-size=\"11\" font-weight=\"700\" fill=\"white\">Python Dash</text>\n  <text x=\"525\" y=\"135\" text-anchor=\"middle\" font-size=\"10\" fill=\"white\">App · Plotly · pandas</text>\n\n  <!-- Nodo 5: Usuario -->\n  <rect x=\"630\" y=\"50\" width=\"120\" height=\"60\" rx=\"8\" fill=\"#f0f4f8\" stroke=\"#8899aa\" stroke-width=\"1.5\"/>\n  <text x=\"690\" y=\"76\" text-anchor=\"middle\" font-size=\"11\" font-weight=\"700\" fill=\"#0f1f3d\">Stakeholder</text>\n  <text x=\"690\" y=\"93\" text-anchor=\"middle\" font-size=\"10\" fill=\"#8899aa\">/ Analista</text>\n\n  <!-- Flecha Power BI → usuario -->\n  <line x1=\"600\" y1=\"42\" x2=\"628\" y2=\"65\" stroke=\"#8899aa\" stroke-width=\"2\" marker-end=\"url(#arr)\"/>\n  <!-- Flecha Dash → usuario -->\n  <line x1=\"600\" y1=\"118\" x2=\"628\" y2=\"95\" stroke=\"#8899aa\" stroke-width=\"2\" marker-end=\"url(#arr)\"/>\n</svg>\n<figcaption style=\"font-size:0.85rem;color:#8899aa;margin-top:0.4rem;\">\n  Arquitectura del proyecto: Python genera los datos, Power BI y Dash los visualizan\n</figcaption>\n</figure>\n```\n\n\n---\n\n## Generación de datos sintéticos\n\nEl script `construccion_analitica.py` genera 11 CSV con datos realistas usando:\n\n- **Perfiles de rendimiento por proyecto** — cada uno tiene un `rc` (ratio de costo final) y `rp` (ratio de plazo) que determinan la trayectoria de CPI/SPI\n- **Curva S sigmoide** — el avance mensual sigue `(s - s0) / (s1 - s0)` para que la forma S sea matemáticamente correcta (sin negativos)\n- **CPI/SPI graduales** — función `factor_mes()` que interpola de 1.0 → rc a lo largo del plazo con inflexión en el 35%, imitando el comportamiento real de obra\n\n::: {#cell-fig-perfiles .cell execution_count=3}\n``` {.python .cell-code code-fold=\"true\"}\ndf_perf = ultimo[[\"id_proyecto\",\"nombre\",\"CPI\",\"SPI\",\"presupuesto_oficial\"]].copy()\ndf_perf[\"color\"] = df_perf[\"CPI\"].apply(sem_color)\ndf_perf[\"tamaño\"] = df_perf[\"presupuesto_oficial\"] / 4e8\n\nfig = go.Figure()\n\n# Zonas de fondo\nfig.add_shape(type=\"rect\", x0=0.85, y0=0.85, x1=0.95, y1=1.05,\n    fillcolor=\"rgba(254,243,226,0.5)\", line_width=0)\nfig.add_shape(type=\"rect\", x0=0.85, y0=0.85, x1=0.85, y1=1.05,\n    fillcolor=\"rgba(253,232,232,0.5)\", line_width=0)\n\n# Líneas de referencia\nfor val, color, dash, label in [\n    (1.0, C[\"green\"], \"dot\", \"Óptimo\"),\n    (0.95, C[\"amber\"], \"dash\", \"Atención\"),\n    (0.85, C[\"red\"], \"dash\", \"Crítico\"),\n]:\n    fig.add_hline(y=val, line_color=color, line_dash=dash, line_width=1.2, opacity=0.6,\n                  annotation_text=f\"SPI {val}\", annotation_position=\"right\",\n                  annotation_font=dict(size=9, color=color))\n    fig.add_vline(x=val, line_color=color, line_dash=dash, line_width=1.2, opacity=0.6)\n\nfor _, row in df_perf.iterrows():\n    fig.add_trace(go.Scatter(\n        x=[row[\"CPI\"]], y=[row[\"SPI\"]],\n        mode=\"markers+text\",\n        marker=dict(size=row[\"tamaño\"], color=row[\"color\"],\n                    opacity=0.85, line=dict(width=2, color=\"white\")),\n        text=[row[\"id_proyecto\"]],\n        textposition=\"middle center\",\n        textfont=dict(size=9, color=\"white\", family=\"Barlow Condensed, sans-serif\"),\n        hovertemplate=(\n            f\"<b>{row['nombre']}</b><br>\"\n            f\"CPI: {row['CPI']:.3f}<br>\"\n            f\"SPI: {row['SPI']:.3f}<br>\"\n            f\"BAC: ${row['presupuesto_oficial']/1e9:.2f} B<extra></extra>\"\n        ),\n        showlegend=False,\n    ))\n\nfig.update_layout(\n    height=380,\n    margin=dict(l=50, r=100, t=30, b=50),\n    paper_bgcolor=\"white\", plot_bgcolor=C[\"slate\"],\n    xaxis=dict(title=\"CPI (Cost Performance Index)\", range=[0.82, 1.04],\n               gridcolor=\"#eef2f7\", tickfont=dict(size=10)),\n    yaxis=dict(title=\"SPI (Schedule Performance Index)\", range=[0.84, 1.02],\n               gridcolor=\"#eef2f7\", tickfont=dict(size=10)),\n    font=dict(family=\"Barlow, sans-serif\", size=11, color=C[\"muted\"]),\n    annotations=[dict(\n        x=0.83, y=1.01,\n        text=\"<b>Tamaño = BAC</b><br>🔴 CPI < 0.85 · 🟡 0.85–0.95 · 🟢 > 0.95\",\n        showarrow=False, font=dict(size=9, color=C[\"muted\"]),\n        bgcolor=\"white\", bordercolor=C[\"muted\"], borderwidth=1,\n    )],\n)\nfig.show()\n```\n\n::: {#fig-perfiles .cell-output .cell-output-display}\n```{=html}\n<div>                            <div id=\"264cdda7-294e-4d1b-94aa-fbf50cd07bed\" class=\"plotly-graph-div\" style=\"height:380px; width:100%;\"></div>            <script type=\"text/javascript\">                require([\"plotly\"], function(Plotly) {                    window.PLOTLYENV=window.PLOTLYENV || {};                                    if (document.getElementById(\"264cdda7-294e-4d1b-94aa-fbf50cd07bed\")) {                    Plotly.newPlot(                        \"264cdda7-294e-4d1b-94aa-fbf50cd07bed\",                        [{\"hovertemplate\":\"\\u003cb\\u003eVia Terciaria Km 12 - Km 28\\u003c\\u002fb\\u003e\\u003cbr\\u003eCPI: 0.881\\u003cbr\\u003eSPI: 0.890\\u003cbr\\u003eBAC: $4.80 B\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"marker\":{\"color\":\"#e17055\",\"line\":{\"color\":\"white\",\"width\":2},\"opacity\":0.85,\"size\":12.0},\"mode\":\"markers+text\",\"showlegend\":false,\"text\":[\"PRY001\"],\"textfont\":{\"color\":\"white\",\"family\":\"Barlow Condensed, sans-serif\",\"size\":9},\"textposition\":\"middle center\",\"x\":[0.8808],\"y\":[0.8897],\"type\":\"scatter\"},{\"hovertemplate\":\"\\u003cb\\u003eEdificio Oficinas Zona Rosa 8 pisos\\u003c\\u002fb\\u003e\\u003cbr\\u003eCPI: 0.963\\u003cbr\\u003eSPI: 0.969\\u003cbr\\u003eBAC: $12.50 B\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"marker\":{\"color\":\"#00b894\",\"line\":{\"color\":\"white\",\"width\":2},\"opacity\":0.85,\"size\":31.25},\"mode\":\"markers+text\",\"showlegend\":false,\"text\":[\"PRY002\"],\"textfont\":{\"color\":\"white\",\"family\":\"Barlow Condensed, sans-serif\",\"size\":9},\"textposition\":\"middle center\",\"x\":[0.9629],\"y\":[0.9694],\"type\":\"scatter\"},{\"hovertemplate\":\"\\u003cb\\u003ePuente Vehicular Rio Magdalena\\u003c\\u002fb\\u003e\\u003cbr\\u003eCPI: 0.850\\u003cbr\\u003eSPI: 0.951\\u003cbr\\u003eBAC: $8.20 B\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"marker\":{\"color\":\"#d63031\",\"line\":{\"color\":\"white\",\"width\":2},\"opacity\":0.85,\"size\":20.5},\"mode\":\"markers+text\",\"showlegend\":false,\"text\":[\"PRY003\"],\"textfont\":{\"color\":\"white\",\"family\":\"Barlow Condensed, sans-serif\",\"size\":9},\"textposition\":\"middle center\",\"x\":[0.8496],\"y\":[0.9507],\"type\":\"scatter\"},{\"hovertemplate\":\"\\u003cb\\u003eParque Industrial Zona Franca\\u003c\\u002fb\\u003e\\u003cbr\\u003eCPI: 0.948\\u003cbr\\u003eSPI: 0.956\\u003cbr\\u003eBAC: $6.40 B\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"marker\":{\"color\":\"#e17055\",\"line\":{\"color\":\"white\",\"width\":2},\"opacity\":0.85,\"size\":16.0},\"mode\":\"markers+text\",\"showlegend\":false,\"text\":[\"PRY004\"],\"textfont\":{\"color\":\"white\",\"family\":\"Barlow Condensed, sans-serif\",\"size\":9},\"textposition\":\"middle center\",\"x\":[0.948],\"y\":[0.9555],\"type\":\"scatter\"},{\"hovertemplate\":\"\\u003cb\\u003eColector Aguas Residuales Zona Norte\\u003c\\u002fb\\u003e\\u003cbr\\u003eCPI: 0.877\\u003cbr\\u003eSPI: 0.944\\u003cbr\\u003eBAC: $3.10 B\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"marker\":{\"color\":\"#e17055\",\"line\":{\"color\":\"white\",\"width\":2},\"opacity\":0.85,\"size\":7.75},\"mode\":\"markers+text\",\"showlegend\":false,\"text\":[\"PRY005\"],\"textfont\":{\"color\":\"white\",\"family\":\"Barlow Condensed, sans-serif\",\"size\":9},\"textposition\":\"middle center\",\"x\":[0.8775],\"y\":[0.944],\"type\":\"scatter\"},{\"hovertemplate\":\"\\u003cb\\u003eAmpliacion Hospital Regional\\u003c\\u002fb\\u003e\\u003cbr\\u003eCPI: 0.993\\u003cbr\\u003eSPI: 0.992\\u003cbr\\u003eBAC: $5.60 B\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"marker\":{\"color\":\"#00b894\",\"line\":{\"color\":\"white\",\"width\":2},\"opacity\":0.85,\"size\":14.0},\"mode\":\"markers+text\",\"showlegend\":false,\"text\":[\"PRY006\"],\"textfont\":{\"color\":\"white\",\"family\":\"Barlow Condensed, sans-serif\",\"size\":9},\"textposition\":\"middle center\",\"x\":[0.9926],\"y\":[0.9921],\"type\":\"scatter\"},{\"hovertemplate\":\"\\u003cb\\u003eEstudio Geotecnico Variante Norte\\u003c\\u002fb\\u003e\\u003cbr\\u003eCPI: 0.978\\u003cbr\\u003eSPI: 0.972\\u003cbr\\u003eBAC: $0.48 B\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"marker\":{\"color\":\"#00b894\",\"line\":{\"color\":\"white\",\"width\":2},\"opacity\":0.85,\"size\":1.2},\"mode\":\"markers+text\",\"showlegend\":false,\"text\":[\"PRY007\"],\"textfont\":{\"color\":\"white\",\"family\":\"Barlow Condensed, sans-serif\",\"size\":9},\"textposition\":\"middle center\",\"x\":[0.9782],\"y\":[0.9723],\"type\":\"scatter\"},{\"hovertemplate\":\"\\u003cb\\u003eUrbanizacion Residencial 200 Casas\\u003c\\u002fb\\u003e\\u003cbr\\u003eCPI: 0.938\\u003cbr\\u003eSPI: 0.937\\u003cbr\\u003eBAC: $9.80 B\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"marker\":{\"color\":\"#e17055\",\"line\":{\"color\":\"white\",\"width\":2},\"opacity\":0.85,\"size\":24.5},\"mode\":\"markers+text\",\"showlegend\":false,\"text\":[\"PRY008\"],\"textfont\":{\"color\":\"white\",\"family\":\"Barlow Condensed, sans-serif\",\"size\":9},\"textposition\":\"middle center\",\"x\":[0.9384],\"y\":[0.9373],\"type\":\"scatter\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmapgl\":[{\"type\":\"heatmapgl\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30}}},\"shapes\":[{\"fillcolor\":\"rgba(254,243,226,0.5)\",\"line\":{\"width\":0},\"type\":\"rect\",\"x0\":0.85,\"x1\":0.95,\"y0\":0.85,\"y1\":1.05},{\"fillcolor\":\"rgba(253,232,232,0.5)\",\"line\":{\"width\":0},\"type\":\"rect\",\"x0\":0.85,\"x1\":0.85,\"y0\":0.85,\"y1\":1.05},{\"line\":{\"color\":\"#00b894\",\"dash\":\"dot\",\"width\":1.2},\"opacity\":0.6,\"type\":\"line\",\"x0\":0,\"x1\":1,\"xref\":\"x domain\",\"y0\":1.0,\"y1\":1.0,\"yref\":\"y\"},{\"line\":{\"color\":\"#00b894\",\"dash\":\"dot\",\"width\":1.2},\"opacity\":0.6,\"type\":\"line\",\"x0\":1.0,\"x1\":1.0,\"xref\":\"x\",\"y0\":0,\"y1\":1,\"yref\":\"y domain\"},{\"line\":{\"color\":\"#e17055\",\"dash\":\"dash\",\"width\":1.2},\"opacity\":0.6,\"type\":\"line\",\"x0\":0,\"x1\":1,\"xref\":\"x domain\",\"y0\":0.95,\"y1\":0.95,\"yref\":\"y\"},{\"line\":{\"color\":\"#e17055\",\"dash\":\"dash\",\"width\":1.2},\"opacity\":0.6,\"type\":\"line\",\"x0\":0.95,\"x1\":0.95,\"xref\":\"x\",\"y0\":0,\"y1\":1,\"yref\":\"y domain\"},{\"line\":{\"color\":\"#d63031\",\"dash\":\"dash\",\"width\":1.2},\"opacity\":0.6,\"type\":\"line\",\"x0\":0,\"x1\":1,\"xref\":\"x domain\",\"y0\":0.85,\"y1\":0.85,\"yref\":\"y\"},{\"line\":{\"color\":\"#d63031\",\"dash\":\"dash\",\"width\":1.2},\"opacity\":0.6,\"type\":\"line\",\"x0\":0.85,\"x1\":0.85,\"xref\":\"x\",\"y0\":0,\"y1\":1,\"yref\":\"y domain\"}],\"annotations\":[{\"font\":{\"color\":\"#8899aa\",\"size\":9},\"showarrow\":false,\"text\":\"\\u003cb\\u003eTama\\u00f1o = BAC\\u003c\\u002fb\\u003e\\u003cbr\\u003e\\ud83d\\udd34 CPI \\u003c 0.85 \\u00b7 \\ud83d\\udfe1 0.85\\u20130.95 \\u00b7 \\ud83d\\udfe2 \\u003e 0.95\",\"x\":0.83,\"xanchor\":\"left\",\"xref\":\"x domain\",\"y\":1.01,\"yanchor\":\"middle\",\"yref\":\"y\",\"bgcolor\":\"white\",\"bordercolor\":\"#8899aa\",\"borderwidth\":1},{\"font\":{\"color\":\"#8899aa\",\"size\":9},\"showarrow\":false,\"text\":\"\\u003cb\\u003eTama\\u00f1o = BAC\\u003c\\u002fb\\u003e\\u003cbr\\u003e\\ud83d\\udd34 CPI \\u003c 0.85 \\u00b7 \\ud83d\\udfe1 0.85\\u20130.95 \\u00b7 \\ud83d\\udfe2 \\u003e 0.95\",\"x\":0.83,\"xanchor\":\"left\",\"xref\":\"x domain\",\"y\":1.01,\"yanchor\":\"middle\",\"yref\":\"y\",\"bgcolor\":\"white\",\"bordercolor\":\"#8899aa\",\"borderwidth\":1},{\"font\":{\"color\":\"#8899aa\",\"size\":9},\"showarrow\":false,\"text\":\"\\u003cb\\u003eTama\\u00f1o = BAC\\u003c\\u002fb\\u003e\\u003cbr\\u003e\\ud83d\\udd34 CPI \\u003c 0.85 \\u00b7 \\ud83d\\udfe1 0.85\\u20130.95 \\u00b7 \\ud83d\\udfe2 \\u003e 0.95\",\"x\":0.83,\"xanchor\":\"left\",\"xref\":\"x domain\",\"y\":1.01,\"yanchor\":\"middle\",\"yref\":\"y\",\"bgcolor\":\"white\",\"bordercolor\":\"#8899aa\",\"borderwidth\":1}],\"margin\":{\"l\":50,\"r\":100,\"t\":30,\"b\":50},\"xaxis\":{\"tickfont\":{\"size\":10},\"title\":{\"text\":\"CPI (Cost Performance Index)\"},\"range\":[0.82,1.04],\"gridcolor\":\"#eef2f7\"},\"yaxis\":{\"tickfont\":{\"size\":10},\"title\":{\"text\":\"SPI (Schedule Performance Index)\"},\"range\":[0.84,1.02],\"gridcolor\":\"#eef2f7\"},\"font\":{\"family\":\"Barlow, sans-serif\",\"size\":11,\"color\":\"#8899aa\"},\"height\":380,\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#f0f4f8\"},                        {\"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('264cdda7-294e-4d1b-94aa-fbf50cd07bed');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };                });            </script>        </div>\n```\n\nPerfiles de rendimiento por proyecto — CPI y SPI al corte Sep 2024\n:::\n:::\n\n\n---\n\n## Curvas S — EVM acumulado\n\nLas curvas S muestran la evolución de **PV** (planeado), **EV** (ganado) y **AC** (costo real) a lo largo del tiempo. La separación entre las tres curvas revela los problemas de desempeño.\n\n::: {#cell-fig-curvas-s .cell execution_count=4}\n``` {.python .cell-code code-fold=\"true\"}\ndf_curvas = (\n    avance.groupby([\"mes_anio\",\"orden_global\"])\n    .agg(PV=(\"PV_acumulado\",\"sum\"), EV=(\"EV_acumulado\",\"sum\"), AC=(\"AC_acumulado\",\"sum\"))\n    .reset_index()\n    .sort_values(\"orden_global\")\n)\n\nfig = go.Figure()\n\ntrazas = [\n    (\"PV\", \"PV Planeado\",    C[\"navy\"],  True),\n    (\"EV\", \"EV Ganado\",      C[\"green\"], False),\n    (\"AC\", \"AC Costo Real\",  C[\"red\"],   False),\n]\n\nfor col, name, color, fill in trazas:\n    r, g, b = int(color[1:3],16), int(color[3:5],16), int(color[5:7],16)\n    fig.add_trace(go.Scatter(\n        x=df_curvas[\"mes_anio\"], y=df_curvas[col]/1e9,\n        mode=\"lines+markers\", name=name,\n        line=dict(color=color, width=2.5),\n        marker=dict(size=5, color=color),\n        fill=\"tozeroy\" if fill else \"none\",\n        fillcolor=f\"rgba({r},{g},{b},0.04)\",\n        hovertemplate=f\"<b>{name}</b><br>%{{x}}<br>${{y:.2f}} B COP<extra></extra>\",\n    ))\n\n# Anotaciones clave\nultimo_mes = df_curvas.iloc[-1]\nfor col, name, color in [(\"PV\",\"PV\",C[\"navy\"]),(\"EV\",\"EV\",C[\"green\"]),(\"AC\",\"AC\",C[\"red\"])]:\n    fig.add_annotation(\n        x=ultimo_mes[\"mes_anio\"], y=ultimo_mes[col]/1e9,\n        text=f\"  <b>{name}: ${ultimo_mes[col]/1e9:.1f}B</b>\",\n        showarrow=False, font=dict(size=10, color=color),\n        xanchor=\"left\",\n    )\n\nfig.update_layout(\n    height=380,\n    margin=dict(l=50, r=120, t=20, b=60),\n    paper_bgcolor=\"white\", plot_bgcolor=C[\"slate\"],\n    legend=dict(orientation=\"h\", y=1.06, font=dict(size=11)),\n    xaxis=dict(title=\"Periodo\", gridcolor=\"#eef2f7\",\n               tickangle=45, tickfont=dict(size=10)),\n    yaxis=dict(title=\"Miles de millones COP\", gridcolor=\"#eef2f7\",\n               tickprefix=\"$\", ticksuffix=\" B\", tickfont=dict(size=10)),\n    font=dict(family=\"Barlow, sans-serif\", size=11, color=C[\"muted\"]),\n)\nfig.show()\n```\n\n::: {#fig-curvas-s .cell-output .cell-output-display}\n```{=html}\n<div>                            <div id=\"e22aa747-cfd3-4b04-b8d2-e7d5be916ee5\" class=\"plotly-graph-div\" style=\"height:380px; width:100%;\"></div>            <script type=\"text/javascript\">                require([\"plotly\"], function(Plotly) {                    window.PLOTLYENV=window.PLOTLYENV || {};                                    if (document.getElementById(\"e22aa747-cfd3-4b04-b8d2-e7d5be916ee5\")) {                    Plotly.newPlot(                        \"e22aa747-cfd3-4b04-b8d2-e7d5be916ee5\",                        [{\"fill\":\"tozeroy\",\"fillcolor\":\"rgba(15,31,61,0.04)\",\"hovertemplate\":\"\\u003cb\\u003ePV Planeado\\u003c\\u002fb\\u003e\\u003cbr\\u003e%{x}\\u003cbr\\u003e${y:.2f} B COP\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"line\":{\"color\":\"#0f1f3d\",\"width\":2.5},\"marker\":{\"color\":\"#0f1f3d\",\"size\":5},\"mode\":\"lines+markers\",\"name\":\"PV Planeado\",\"x\":[\"Mar-23\",\"Abr-23\",\"May-23\",\"Jun-23\",\"Jul-23\",\"Ago-23\",\"Sep-23\",\"Oct-23\",\"Nov-23\",\"Dic-23\",\"Ene-24\",\"Feb-24\",\"Mar-24\",\"Abr-24\",\"May-24\",\"Jun-24\",\"Jul-24\",\"Ago-24\"],\"y\":[0.098933532,0.23624858,0.42541176,0.683326279,1.03007835,1.556257062,2.34822095,3.405427613,4.862741309,6.719232017,9.021328629,11.722736299,14.770488124,18.073561425,21.667857282,25.573192602,29.71258116,33.863341906],\"type\":\"scatter\"},{\"fill\":\"none\",\"fillcolor\":\"rgba(0,184,148,0.04)\",\"hovertemplate\":\"\\u003cb\\u003eEV Ganado\\u003c\\u002fb\\u003e\\u003cbr\\u003e%{x}\\u003cbr\\u003e${y:.2f} B COP\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"line\":{\"color\":\"#00b894\",\"width\":2.5},\"marker\":{\"color\":\"#00b894\",\"size\":5},\"mode\":\"lines+markers\",\"name\":\"EV Ganado\",\"x\":[\"Mar-23\",\"Abr-23\",\"May-23\",\"Jun-23\",\"Jul-23\",\"Ago-23\",\"Sep-23\",\"Oct-23\",\"Nov-23\",\"Dic-23\",\"Ene-24\",\"Feb-24\",\"Mar-24\",\"Abr-24\",\"May-24\",\"Jun-24\",\"Jul-24\",\"Ago-24\"],\"y\":[0.101626202,0.240198339,0.427942176,0.687361584,1.037933029,1.565299382,2.341889858,3.400972203,4.848259856,6.612440648,8.778733241,11.332198625,14.197869018,17.320200089,20.72531719,24.417200402,28.264022492,32.103918953],\"type\":\"scatter\"},{\"fill\":\"none\",\"fillcolor\":\"rgba(214,48,49,0.04)\",\"hovertemplate\":\"\\u003cb\\u003eAC Costo Real\\u003c\\u002fb\\u003e\\u003cbr\\u003e%{x}\\u003cbr\\u003e${y:.2f} B COP\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"line\":{\"color\":\"#d63031\",\"width\":2.5},\"marker\":{\"color\":\"#d63031\",\"size\":5},\"mode\":\"lines+markers\",\"name\":\"AC Costo Real\",\"x\":[\"Mar-23\",\"Abr-23\",\"May-23\",\"Jun-23\",\"Jul-23\",\"Ago-23\",\"Sep-23\",\"Oct-23\",\"Nov-23\",\"Dic-23\",\"Ene-24\",\"Feb-24\",\"Mar-24\",\"Abr-24\",\"May-24\",\"Jun-24\",\"Jul-24\",\"Ago-24\"],\"y\":[0.102157611,0.240356804,0.432518565,0.694263866,1.049933899,1.583533727,2.373114695,3.485699049,5.054905146,6.974194521,9.284880199,12.08043331,15.259158547,18.817068331,22.4953062,26.480762133,30.62147191,34.792326518],\"type\":\"scatter\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmapgl\":[{\"type\":\"heatmapgl\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30}}},\"annotations\":[{\"font\":{\"color\":\"#0f1f3d\",\"size\":10},\"showarrow\":false,\"text\":\"  \\u003cb\\u003ePV: $33.9B\\u003c\\u002fb\\u003e\",\"x\":\"Ago-24\",\"xanchor\":\"left\",\"y\":33.863341906},{\"font\":{\"color\":\"#00b894\",\"size\":10},\"showarrow\":false,\"text\":\"  \\u003cb\\u003eEV: $32.1B\\u003c\\u002fb\\u003e\",\"x\":\"Ago-24\",\"xanchor\":\"left\",\"y\":32.103918953},{\"font\":{\"color\":\"#d63031\",\"size\":10},\"showarrow\":false,\"text\":\"  \\u003cb\\u003eAC: $34.8B\\u003c\\u002fb\\u003e\",\"x\":\"Ago-24\",\"xanchor\":\"left\",\"y\":34.792326518}],\"margin\":{\"l\":50,\"r\":120,\"t\":20,\"b\":60},\"legend\":{\"font\":{\"size\":11},\"orientation\":\"h\",\"y\":1.06},\"xaxis\":{\"tickfont\":{\"size\":10},\"title\":{\"text\":\"Periodo\"},\"gridcolor\":\"#eef2f7\",\"tickangle\":45},\"yaxis\":{\"tickfont\":{\"size\":10},\"title\":{\"text\":\"Miles de millones COP\"},\"gridcolor\":\"#eef2f7\",\"tickprefix\":\"$\",\"ticksuffix\":\" B\"},\"font\":{\"family\":\"Barlow, sans-serif\",\"size\":11,\"color\":\"#8899aa\"},\"height\":380,\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#f0f4f8\"},                        {\"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('e22aa747-cfd3-4b04-b8d2-e7d5be916ee5');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };                });            </script>        </div>\n```\n\nCurvas S consolidadas del portafolio — Mar 2023 a Sep 2024\n:::\n:::\n\n\n::: {.callout-tip}\n**Lectura de la curva S:** cuando AC > PV hay sobrecosto frente a lo planeado. Cuando EV < PV hay retraso de cronograma. La brecha AC − EV es la variación de costo (CV = $\\-2\\.688 B COP).\n:::\n\n---\n\n## Presupuesto APU\n\nEl **Análisis de Precios Unitarios** descompone el presupuesto en cuatro componentes estándar del sector. Los rangos son validados contra referencias de Camacol y SENA.\n\n::: {#cell-fig-apu .cell execution_count=5}\n``` {.python .cell-code code-fold=\"true\"}\napu = D[\"fact_presupuesto_apu\"]\ndim_cap = D[\"dim_capitulo\"].rename(columns={\"nombre\":\"nombre_capitulo\"})\ncaps = apu.merge(dim_cap, left_on=\"id_capitulo\", right_on=\"id_cap\")\n\ncomp_tot = apu.groupby(\"componente\")[\"presupuesto_oficial\"].sum().sort_values(ascending=False)\ncaps_tot = caps.groupby(\"nombre_capitulo\")[\"presupuesto_oficial\"].sum().sort_values(ascending=False).head(8)\n\nfig = make_subplots(\n    rows=1, cols=2,\n    specs=[[{\"type\":\"pie\"}, {\"type\":\"bar\"}]],\n    subplot_titles=[\"Composición por componente\", \"Top 8 capítulos de obra\"],\n)\n\n# Donut\ncolores_comp = [C[\"blue\"], C[\"green\"], C[\"amber\"], C[\"gold\"]]\nfig.add_trace(go.Pie(\n    labels=comp_tot.index,\n    values=comp_tot.values,\n    hole=0.6,\n    marker_colors=colores_comp,\n    textinfo=\"percent+label\",\n    textfont=dict(size=10),\n    hovertemplate=\"<b>%{label}</b><br>$%{value:.2e}<br>%{percent}<extra></extra>\",\n), row=1, col=1)\n\n# Barras horizontales\ncolores_cap = [C[\"navy\"], C[\"navy\"], \"#2d4a8a\", C[\"gold\"], C[\"gold\"],\n               C[\"green\"], C[\"blue\"], C[\"amber\"]]\nfig.add_trace(go.Bar(\n    y=caps_tot.index,\n    x=caps_tot.values/1e9,\n    orientation=\"h\",\n    marker_color=colores_cap,\n    text=[f\"${v/1e9:.1f}B\" for v in caps_tot.values],\n    textposition=\"outside\",\n    textfont=dict(size=10),\n    hovertemplate=\"<b>%{y}</b><br>$%{x:.3f} B COP<extra></extra>\",\n), row=1, col=2)\n\nfig.update_layout(\n    height=380,\n    margin=dict(l=10, r=80, t=40, b=10),\n    paper_bgcolor=\"white\",\n    showlegend=False,\n    font=dict(family=\"Barlow, sans-serif\", size=10, color=C[\"muted\"]),\n)\nfig.update_xaxes(\n    row=1, col=2,\n    tickprefix=\"$\", ticksuffix=\" B\",\n    gridcolor=\"#eef2f7\",\n)\nfig.update_yaxes(row=1, col=2, tickfont=dict(size=9))\nfig.show()\n```\n\n::: {#fig-apu .cell-output .cell-output-display}\n```{=html}\n<div>                            <div id=\"4e2453d9-cab0-4a4f-aef9-63450f25538a\" class=\"plotly-graph-div\" style=\"height:380px; width:100%;\"></div>            <script type=\"text/javascript\">                require([\"plotly\"], function(Plotly) {                    window.PLOTLYENV=window.PLOTLYENV || {};                                    if (document.getElementById(\"4e2453d9-cab0-4a4f-aef9-63450f25538a\")) {                    Plotly.newPlot(                        \"4e2453d9-cab0-4a4f-aef9-63450f25538a\",                        [{\"hole\":0.6,\"hovertemplate\":\"\\u003cb\\u003e%{label}\\u003c\\u002fb\\u003e\\u003cbr\\u003e$%{value:.2e}\\u003cbr\\u003e%{percent}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"labels\":[\"Materiales\",\"Mano de Obra\",\"Equipo\",\"AI\"],\"marker\":{\"colors\":[\"#3b82f6\",\"#00b894\",\"#e17055\",\"#c9a84c\"]},\"textfont\":{\"size\":10},\"textinfo\":\"percent+label\",\"values\":[24422399999,14246400001,6614399999,5596800001],\"type\":\"pie\",\"domain\":{\"x\":[0.0,0.45],\"y\":[0.0,1.0]}},{\"hovertemplate\":\"\\u003cb\\u003e%{y}\\u003c\\u002fb\\u003e\\u003cbr\\u003e$%{x:.3f} B COP\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"marker\":{\"color\":[\"#0f1f3d\",\"#0f1f3d\",\"#2d4a8a\",\"#c9a84c\",\"#c9a84c\",\"#00b894\",\"#3b82f6\",\"#e17055\"]},\"orientation\":\"h\",\"text\":[\"$11.1B\",\"$7.5B\",\"$6.7B\",\"$6.4B\",\"$4.8B\",\"$3.7B\",\"$2.7B\",\"$2.1B\"],\"textfont\":{\"size\":10},\"textposition\":\"outside\",\"x\":[11.107594601,7.506359551,6.697973034,6.399242283,4.755753196,3.672310345,2.651149425,2.083045978],\"y\":[\"Estructura en Concreto\",\"Vias y Pavimentos\",\"Movimiento de Tierra\",\"Instalaciones Hidrosanitarias\",\"Instalaciones Electricas\",\"Cimentacion y Pilotaje\",\"Mamposteria y Muros\",\"Acabados Interiores\"],\"type\":\"bar\",\"xaxis\":\"x\",\"yaxis\":\"y\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmapgl\":[{\"type\":\"heatmapgl\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30}}},\"xaxis\":{\"anchor\":\"y\",\"domain\":[0.55,1.0],\"tickprefix\":\"$\",\"ticksuffix\":\" B\",\"gridcolor\":\"#eef2f7\"},\"yaxis\":{\"anchor\":\"x\",\"domain\":[0.0,1.0],\"tickfont\":{\"size\":9}},\"annotations\":[{\"font\":{\"size\":16},\"showarrow\":false,\"text\":\"Composici\\u00f3n por componente\",\"x\":0.225,\"xanchor\":\"center\",\"xref\":\"paper\",\"y\":1.0,\"yanchor\":\"bottom\",\"yref\":\"paper\"},{\"font\":{\"size\":16},\"showarrow\":false,\"text\":\"Top 8 cap\\u00edtulos de obra\",\"x\":0.775,\"xanchor\":\"center\",\"xref\":\"paper\",\"y\":1.0,\"yanchor\":\"bottom\",\"yref\":\"paper\"}],\"margin\":{\"l\":10,\"r\":80,\"t\":40,\"b\":10},\"font\":{\"family\":\"Barlow, sans-serif\",\"size\":10,\"color\":\"#8899aa\"},\"height\":380,\"paper_bgcolor\":\"white\",\"showlegend\":false},                        {\"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('4e2453d9-cab0-4a4f-aef9-63450f25538a');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };                });            </script>        </div>\n```\n\nDistribución del presupuesto APU por componente y por capítulo de obra\n:::\n:::\n\n\nLos rangos observados (Materiales 48%, MO 28%, Equipo 13%, AIU 11%) están dentro de los estándares sectoriales colombianos para obra civil mixta.\n\n---\n\n## Modelo predictivo CRISP-DM\n\n### Metodología\n\nEl modelo predice el **EAC (Estimate at Completion)** usando regresión lineal simple sobre los datos históricos de cada proyecto:\n\n$$\\text{AC\\_acum}(t) = \\beta_0 + \\beta_1 \\cdot t + \\epsilon$$\n\nDonde $t$ es el mes relativo del proyecto. El EAC final se calcula extrapolando hasta el plazo contractual.\n\n**Adicionalmente**, se usa el método EVM clásico:\n\n$$\\text{EAC}_{CPI} = \\frac{\\text{BAC}}{\\text{CPI}_{\\text{reciente}}}$$\n\nAmbos métodos se comparan y el modelo reporta R², MAE y RMSE por proyecto.\n\n### Resultados del modelo\n\n::: {#cell-fig-predicciones .cell execution_count=6}\n``` {.python .cell-code code-fold=\"true\"}\ndf_pred = pred.copy()\ndf_pred = df_pred.sort_values(\"pct_desviacion_est\", ascending=True)\n\ncolores_pred = [\n    C[\"red\"] if v > 10 else (C[\"amber\"] if v > 5 else C[\"green\"])\n    for v in df_pred[\"pct_desviacion_est\"]\n]\n\nfig = go.Figure()\n\nfig.add_trace(go.Bar(\n    y=df_pred[\"nombre_proyecto\"],\n    x=df_pred[\"BAC\"]/1e9,\n    orientation=\"h\",\n    name=\"BAC\",\n    marker_color=C[\"navy\"],\n    opacity=0.5,\n    hovertemplate=\"<b>%{y}</b><br>BAC: $%{x:.3f} B<extra></extra>\",\n))\n\nfig.add_trace(go.Bar(\n    y=df_pred[\"nombre_proyecto\"],\n    x=df_pred[\"EAC_por_CPI\"]/1e9,\n    orientation=\"h\",\n    name=\"EAC\",\n    marker_color=colores_pred,\n    opacity=0.85,\n    hovertemplate=\"<b>%{y}</b><br>EAC: $%{x:.3f} B<extra></extra>\",\n))\n\n# Anotaciones desviación\nfor _, row in df_pred.iterrows():\n    fig.add_annotation(\n        y=row[\"nombre_proyecto\"],\n        x=row[\"EAC_por_CPI\"]/1e9,\n        text=f\"  <b>+{row['pct_desviacion_est']:.1f}%</b>  R²={row['R2_modelo']:.3f}\",\n        showarrow=False,\n        font=dict(size=9, color=C[\"red\"] if row[\"pct_desviacion_est\"] > 10 else C[\"muted\"]),\n        xanchor=\"left\",\n    )\n\nfig.update_layout(\n    barmode=\"overlay\",\n    height=380,\n    margin=dict(l=10, r=200, t=20, b=40),\n    paper_bgcolor=\"white\", plot_bgcolor=C[\"slate\"],\n    legend=dict(orientation=\"h\", y=1.06, font=dict(size=11)),\n    xaxis=dict(title=\"Miles de millones COP\", gridcolor=\"#eef2f7\",\n               tickprefix=\"$\", ticksuffix=\" B\", tickfont=dict(size=10)),\n    yaxis=dict(tickfont=dict(size=10)),\n    font=dict(family=\"Barlow, sans-serif\", size=11, color=C[\"muted\"]),\n)\nfig.show()\n```\n\n::: {#fig-predicciones .cell-output .cell-output-display}\n```{=html}\n<div>                            <div id=\"fa8a79b0-4faa-4db0-ad73-d27002a779b2\" class=\"plotly-graph-div\" style=\"height:380px; width:100%;\"></div>            <script type=\"text/javascript\">                require([\"plotly\"], function(Plotly) {                    window.PLOTLYENV=window.PLOTLYENV || {};                                    if (document.getElementById(\"fa8a79b0-4faa-4db0-ad73-d27002a779b2\")) {                    Plotly.newPlot(                        \"fa8a79b0-4faa-4db0-ad73-d27002a779b2\",                        [{\"hovertemplate\":\"\\u003cb\\u003e%{y}\\u003c\\u002fb\\u003e\\u003cbr\\u003eBAC: $%{x:.3f} B\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"marker\":{\"color\":\"#0f1f3d\"},\"name\":\"BAC\",\"opacity\":0.5,\"orientation\":\"h\",\"x\":[5.6,0.48,12.5,6.4,9.8,4.8,3.1,8.2],\"y\":[\"Ampliacion Hospital Regional\",\"Estudio Geotecnico Variante Norte\",\"Edificio Oficinas Zona Rosa 8 pisos\",\"Parque Industrial Zona Franca\",\"Urbanizacion Residencial 200 Casas\",\"Via Terciaria Km 12 - Km 28\",\"Colector Aguas Residuales Zona Norte\",\"Puente Vehicular Rio Magdalena\"],\"type\":\"bar\"},{\"hovertemplate\":\"\\u003cb\\u003e%{y}\\u003c\\u002fb\\u003e\\u003cbr\\u003eEAC: $%{x:.3f} B\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"marker\":{\"color\":[\"#00b894\",\"#00b894\",\"#00b894\",\"#e17055\",\"#e17055\",\"#d63031\",\"#d63031\",\"#d63031\"]},\"name\":\"EAC\",\"opacity\":0.85,\"orientation\":\"h\",\"x\":[5.654852065,0.485911928,12.970392916,6.72716443,10.391630143,5.453099557,3.573349727,9.746820397],\"y\":[\"Ampliacion Hospital Regional\",\"Estudio Geotecnico Variante Norte\",\"Edificio Oficinas Zona Rosa 8 pisos\",\"Parque Industrial Zona Franca\",\"Urbanizacion Residencial 200 Casas\",\"Via Terciaria Km 12 - Km 28\",\"Colector Aguas Residuales Zona Norte\",\"Puente Vehicular Rio Magdalena\"],\"type\":\"bar\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmapgl\":[{\"type\":\"heatmapgl\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30}}},\"annotations\":[{\"font\":{\"color\":\"#8899aa\",\"size\":9},\"showarrow\":false,\"text\":\"  \\u003cb\\u003e+1.0%\\u003c\\u002fb\\u003e  R\\u00b2=0.937\",\"x\":5.654852065,\"xanchor\":\"left\",\"y\":\"Ampliacion Hospital Regional\"},{\"font\":{\"color\":\"#8899aa\",\"size\":9},\"showarrow\":false,\"text\":\"  \\u003cb\\u003e+1.2%\\u003c\\u002fb\\u003e  R\\u00b2=0.961\",\"x\":0.485911928,\"xanchor\":\"left\",\"y\":\"Estudio Geotecnico Variante Norte\"},{\"font\":{\"color\":\"#8899aa\",\"size\":9},\"showarrow\":false,\"text\":\"  \\u003cb\\u003e+3.8%\\u003c\\u002fb\\u003e  R\\u00b2=0.969\",\"x\":12.970392916,\"xanchor\":\"left\",\"y\":\"Edificio Oficinas Zona Rosa 8 pisos\"},{\"font\":{\"color\":\"#8899aa\",\"size\":9},\"showarrow\":false,\"text\":\"  \\u003cb\\u003e+5.1%\\u003c\\u002fb\\u003e  R\\u00b2=0.918\",\"x\":6.72716443,\"xanchor\":\"left\",\"y\":\"Parque Industrial Zona Franca\"},{\"font\":{\"color\":\"#8899aa\",\"size\":9},\"showarrow\":false,\"text\":\"  \\u003cb\\u003e+6.0%\\u003c\\u002fb\\u003e  R\\u00b2=0.933\",\"x\":10.391630143,\"xanchor\":\"left\",\"y\":\"Urbanizacion Residencial 200 Casas\"},{\"font\":{\"color\":\"#d63031\",\"size\":9},\"showarrow\":false,\"text\":\"  \\u003cb\\u003e+13.6%\\u003c\\u002fb\\u003e  R\\u00b2=0.971\",\"x\":5.453099557,\"xanchor\":\"left\",\"y\":\"Via Terciaria Km 12 - Km 28\"},{\"font\":{\"color\":\"#d63031\",\"size\":9},\"showarrow\":false,\"text\":\"  \\u003cb\\u003e+15.3%\\u003c\\u002fb\\u003e  R\\u00b2=0.961\",\"x\":3.573349727,\"xanchor\":\"left\",\"y\":\"Colector Aguas Residuales Zona Norte\"},{\"font\":{\"color\":\"#d63031\",\"size\":9},\"showarrow\":false,\"text\":\"  \\u003cb\\u003e+18.9%\\u003c\\u002fb\\u003e  R\\u00b2=0.945\",\"x\":9.746820397,\"xanchor\":\"left\",\"y\":\"Puente Vehicular Rio Magdalena\"}],\"margin\":{\"l\":10,\"r\":200,\"t\":20,\"b\":40},\"legend\":{\"font\":{\"size\":11},\"orientation\":\"h\",\"y\":1.06},\"xaxis\":{\"tickfont\":{\"size\":10},\"title\":{\"text\":\"Miles de millones COP\"},\"gridcolor\":\"#eef2f7\",\"tickprefix\":\"$\",\"ticksuffix\":\" B\"},\"yaxis\":{\"tickfont\":{\"size\":10}},\"font\":{\"family\":\"Barlow, sans-serif\",\"size\":11,\"color\":\"#8899aa\"},\"barmode\":\"overlay\",\"height\":380,\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#f0f4f8\"},                        {\"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('fa8a79b0-4faa-4db0-ad73-d27002a779b2');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };                });            </script>        </div>\n```\n\nEAC predicho vs BAC por proyecto — desviación estimada al cierre\n:::\n:::\n\n\n::: {#tbl-modelo .cell tbl-cap='Métricas del modelo predictivo por proyecto' execution_count=7}\n``` {.python .cell-code}\ntbl = df_pred[[\"nombre_proyecto\",\"semaforo\",\"CPI_reciente\",\"SPI_reciente\",\n               \"EAC_por_CPI\",\"R2_modelo\",\"MAE_modelo\",\"pct_desviacion_est\"]].copy()\ntbl.columns = [\"Proyecto\",\"Nivel\",\"CPI\",\"SPI\",\"EAC (COP)\",\"R²\",\"MAE (COP)\",\"Desv %\"]\ntbl[\"CPI\"]      = tbl[\"CPI\"].apply(lambda v: f\"{v:.3f}\")\ntbl[\"SPI\"]      = tbl[\"SPI\"].apply(lambda v: f\"{v:.3f}\")\ntbl[\"EAC (COP)\"]= tbl[\"EAC (COP)\"].apply(lambda v: f\"${v/1e9:.3f} B\")\ntbl[\"R²\"]       = tbl[\"R²\"].apply(lambda v: f\"{v:.3f}\")\ntbl[\"MAE (COP)\"]= tbl[\"MAE (COP)\"].apply(lambda v: f\"${v/1e6:.0f} M\")\ntbl[\"Desv %\"]   = tbl[\"Desv %\"].apply(lambda v: f\"+{v:.1f}%\")\ntbl = tbl.sort_values(\"Desv %\", ascending=False).set_index(\"Proyecto\")\ntbl\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Nivel</th>\n      <th>CPI</th>\n      <th>SPI</th>\n      <th>EAC (COP)</th>\n      <th>R²</th>\n      <th>MAE (COP)</th>\n      <th>Desv %</th>\n    </tr>\n    <tr>\n      <th>Proyecto</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Urbanizacion Residencial 200 Casas</th>\n      <td>ATENCION</td>\n      <td>0.943</td>\n      <td>0.945</td>\n      <td>$10.392 B</td>\n      <td>0.933</td>\n      <td>$465 M</td>\n      <td>+6.0%</td>\n    </tr>\n    <tr>\n      <th>Parque Industrial Zona Franca</th>\n      <td>NORMAL</td>\n      <td>0.951</td>\n      <td>0.973</td>\n      <td>$6.727 B</td>\n      <td>0.918</td>\n      <td>$153 M</td>\n      <td>+5.1%</td>\n    </tr>\n    <tr>\n      <th>Edificio Oficinas Zona Rosa 8 pisos</th>\n      <td>NORMAL</td>\n      <td>0.964</td>\n      <td>0.970</td>\n      <td>$12.970 B</td>\n      <td>0.969</td>\n      <td>$598 M</td>\n      <td>+3.8%</td>\n    </tr>\n    <tr>\n      <th>Puente Vehicular Rio Magdalena</th>\n      <td>CRITICO</td>\n      <td>0.841</td>\n      <td>0.959</td>\n      <td>$9.747 B</td>\n      <td>0.945</td>\n      <td>$410 M</td>\n      <td>+18.9%</td>\n    </tr>\n    <tr>\n      <th>Colector Aguas Residuales Zona Norte</th>\n      <td>ATENCION</td>\n      <td>0.868</td>\n      <td>0.955</td>\n      <td>$3.573 B</td>\n      <td>0.961</td>\n      <td>$143 M</td>\n      <td>+15.3%</td>\n    </tr>\n    <tr>\n      <th>Via Terciaria Km 12 - Km 28</th>\n      <td>ATENCION</td>\n      <td>0.880</td>\n      <td>0.890</td>\n      <td>$5.453 B</td>\n      <td>0.971</td>\n      <td>$265 M</td>\n      <td>+13.6%</td>\n    </tr>\n    <tr>\n      <th>Estudio Geotecnico Variante Norte</th>\n      <td>NORMAL</td>\n      <td>0.988</td>\n      <td>0.991</td>\n      <td>$0.486 B</td>\n      <td>0.961</td>\n      <td>$19 M</td>\n      <td>+1.2%</td>\n    </tr>\n    <tr>\n      <th>Ampliacion Hospital Regional</th>\n      <td>NORMAL</td>\n      <td>0.990</td>\n      <td>1.002</td>\n      <td>$5.655 B</td>\n      <td>0.937</td>\n      <td>$122 M</td>\n      <td>+1.0%</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {.callout-warning}\n**PRY003 — Puente Vehicular Río Magdalena** presenta la mayor desviación estimada (+18.9%) con un CPI de 0.850, en umbral crítico. Requiere revisión del plan de trabajo y posible adición contractual.\n:::\n\n---\n\n## Contratos y adiciones\n\n::: {#cell-fig-contratos .cell execution_count=8}\n``` {.python .cell-code code-fold=\"true\"}\ncto = contratos.copy()\nadds_por_proy = (\n    D[\"fact_adiciones\"]\n    .groupby(\"id_proyecto\")[\"valor\"]\n    .sum()\n    .rename(\"val_adds\")\n)\ncto = cto.merge(adds_por_proy, on=\"id_proyecto\", how=\"left\").fillna({\"val_adds\": 0})\ncto[\"pct_adds\"] = cto[\"val_adds\"] / cto[\"valor_contrato\"] * 100\n\nfig = go.Figure()\n\ncolores_cto = [C[\"red\"] if v > 0 else C[\"green\"] for v in cto[\"val_adds\"]]\n\nfig.add_trace(go.Scatter(\n    x=cto[\"descuento_oferta_pct\"],\n    y=cto[\"pct_adds\"],\n    mode=\"markers+text\",\n    text=cto[\"id_proyecto\"],\n    textposition=\"top center\",\n    textfont=dict(size=10, family=\"Barlow Condensed, sans-serif\"),\n    marker=dict(\n        size=16, color=colores_cto, opacity=0.85,\n        line=dict(width=2, color=\"white\"),\n    ),\n    hovertemplate=(\n        \"<b>%{text}</b><br>\"\n        \"Descuento oferta: %{x:.1f}%<br>\"\n        \"% Adiciones: %{y:.1f}%<extra></extra>\"\n    ),\n))\n\n# Línea de tendencia manual\nimport numpy as np\nif len(cto) > 2:\n    z = np.polyfit(cto[\"descuento_oferta_pct\"], cto[\"pct_adds\"], 1)\n    p = np.poly1d(z)\n    x_line = np.linspace(cto[\"descuento_oferta_pct\"].min(), cto[\"descuento_oferta_pct\"].max(), 50)\n    fig.add_trace(go.Scatter(\n        x=x_line, y=p(x_line),\n        mode=\"lines\", name=\"Tendencia\",\n        line=dict(color=C[\"amber\"], dash=\"dash\", width=1.5),\n        showlegend=True,\n    ))\n\nfig.add_vline(x=12, line_dash=\"dash\", line_color=C[\"amber\"], opacity=0.5,\n              annotation_text=\"Umbral descuento agresivo (12%)\",\n              annotation_font=dict(size=9))\n\nfig.update_layout(\n    height=360,\n    margin=dict(l=50, r=30, t=20, b=50),\n    paper_bgcolor=\"white\", plot_bgcolor=C[\"slate\"],\n    xaxis=dict(title=\"Descuento de oferta (%)\", gridcolor=\"#eef2f7\", tickfont=dict(size=10)),\n    yaxis=dict(title=\"% Adiciones / Valor contrato\", gridcolor=\"#eef2f7\", tickfont=dict(size=10)),\n    font=dict(family=\"Barlow, sans-serif\", size=11, color=C[\"muted\"]),\n    legend=dict(font=dict(size=10)),\n)\nfig.show()\n```\n\n::: {#fig-contratos .cell-output .cell-output-display}\n```{=html}\n<div>                            <div id=\"4add685a-69b1-4bff-9c28-e5e26509e2ee\" class=\"plotly-graph-div\" style=\"height:360px; width:100%;\"></div>            <script type=\"text/javascript\">                require([\"plotly\"], function(Plotly) {                    window.PLOTLYENV=window.PLOTLYENV || {};                                    if (document.getElementById(\"4add685a-69b1-4bff-9c28-e5e26509e2ee\")) {                    Plotly.newPlot(                        \"4add685a-69b1-4bff-9c28-e5e26509e2ee\",                        [{\"hovertemplate\":\"\\u003cb\\u003e%{text}\\u003c\\u002fb\\u003e\\u003cbr\\u003eDescuento oferta: %{x:.1f}%\\u003cbr\\u003e% Adiciones: %{y:.1f}%\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"marker\":{\"color\":[\"#d63031\",\"#d63031\",\"#d63031\",\"#d63031\",\"#d63031\",\"#00b894\",\"#00b894\",\"#00b894\"],\"line\":{\"color\":\"white\",\"width\":2},\"opacity\":0.85,\"size\":16},\"mode\":\"markers+text\",\"text\":[\"PRY001\",\"PRY002\",\"PRY003\",\"PRY004\",\"PRY005\",\"PRY006\",\"PRY007\",\"PRY008\"],\"textfont\":{\"family\":\"Barlow Condensed, sans-serif\",\"size\":10},\"textposition\":\"top center\",\"x\":[15.52,3.26,13.47,3.07,17.0,9.58,16.46,3.93],\"y\":[16.19579535941531,14.427365257975039,12.336618238862993,14.401738604871985,16.323721553392012,0.0,0.0,0.0],\"type\":\"scatter\"},{\"line\":{\"color\":\"#e17055\",\"dash\":\"dash\",\"width\":1.5},\"mode\":\"lines\",\"name\":\"Tendencia\",\"showlegend\":true,\"x\":[3.07,3.354285714285714,3.6385714285714283,3.9228571428571426,4.207142857142857,4.491428571428571,4.775714285714285,5.06,5.344285714285714,5.628571428571428,5.912857142857142,6.197142857142857,6.481428571428571,6.765714285714285,7.049999999999999,7.3342857142857145,7.618571428571428,7.902857142857142,8.187142857142856,8.471428571428572,8.755714285714285,9.04,9.324285714285713,9.608571428571429,9.892857142857142,10.177142857142856,10.46142857142857,10.745714285714286,11.03,11.314285714285713,11.598571428571429,11.882857142857143,12.167142857142856,12.45142857142857,12.735714285714284,13.02,13.304285714285713,13.588571428571427,13.872857142857143,14.157142857142857,14.44142857142857,14.725714285714284,15.009999999999998,15.294285714285714,15.578571428571427,15.862857142857141,16.147142857142857,16.43142857142857,16.715714285714284,17.0],\"y\":[8.433291201198536,8.4639156096908,8.494540018183065,8.525164426675328,8.555788835167592,8.586413243659857,8.61703765215212,8.647662060644384,8.678286469136648,8.708910877628913,8.739535286121177,8.77015969461344,8.800784103105705,8.831408511597969,8.862032920090233,8.892657328582498,8.923281737074761,8.953906145567025,8.984530554059289,9.015154962551554,9.045779371043817,9.076403779536081,9.107028188028345,9.13765259652061,9.168277005012873,9.198901413505137,9.229525821997402,9.260150230489666,9.29077463898193,9.321399047474195,9.352023455966458,9.382647864458722,9.413272272950987,9.44389668144325,9.474521089935514,9.505145498427778,9.535769906920043,9.566394315412307,9.59701872390457,9.627643132396834,9.6582675408891,9.688891949381363,9.719516357873626,9.750140766365892,9.780765174858155,9.811389583350419,9.842013991842684,9.872638400334948,9.903262808827211,9.933887217319477],\"type\":\"scatter\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmapgl\":[{\"type\":\"heatmapgl\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30}}},\"shapes\":[{\"line\":{\"color\":\"#e17055\",\"dash\":\"dash\"},\"opacity\":0.5,\"type\":\"line\",\"x0\":12,\"x1\":12,\"xref\":\"x\",\"y0\":0,\"y1\":1,\"yref\":\"y domain\"}],\"annotations\":[{\"font\":{\"size\":9},\"showarrow\":false,\"text\":\"Umbral descuento agresivo (12%)\",\"x\":12,\"xanchor\":\"left\",\"xref\":\"x\",\"y\":1,\"yanchor\":\"top\",\"yref\":\"y domain\"}],\"margin\":{\"l\":50,\"r\":30,\"t\":20,\"b\":50},\"xaxis\":{\"tickfont\":{\"size\":10},\"title\":{\"text\":\"Descuento de oferta (%)\"},\"gridcolor\":\"#eef2f7\"},\"yaxis\":{\"tickfont\":{\"size\":10},\"title\":{\"text\":\"% Adiciones \\u002f Valor contrato\"},\"gridcolor\":\"#eef2f7\"},\"font\":{\"family\":\"Barlow, sans-serif\",\"size\":11,\"color\":\"#8899aa\"},\"legend\":{\"font\":{\"size\":10}},\"height\":360,\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#f0f4f8\"},                        {\"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('4add685a-69b1-4bff-9c28-e5e26509e2ee');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };                });            </script>        </div>\n```\n\nDescuento de oferta vs porcentaje de adiciones por contrato\n:::\n:::\n\n\n**Hallazgo:** existe correlación positiva entre descuentos de oferta agresivos (>12%) y mayor porcentaje de adiciones posteriores — consistente con el fenómeno de *desequilibrio de precios unitarios* documentado en el sector público colombiano.\n\n---\n\n## Dashboards\n\nLas siguientes capturas muestran el dashboard en sus dos implementaciones. Ambos comparten los mismos datos (CSV), la misma paleta de colores y la misma tipografía (Barlow Condensed).\n\n### Power BI\n\n::: {.grid}\n::: {.g-col-12}\n![Página 1 — Portafolio ejecutivo con semáforos CPI/SPI y scatter por proyecto](img/powerbi_p1.png){.lightbox fig-alt=\"Dashboard Power BI página 1\"}\n:::\n::: {.g-col-6}\n![Página 2 — Curvas S y evolución EVM mensual](img/powerbi_p2.png){.lightbox fig-alt=\"Dashboard Power BI página 2\"}\n:::\n::: {.g-col-6}\n![Página 3 — Presupuesto APU por capítulo y componente](img/powerbi_p3.png){.lightbox fig-alt=\"Dashboard Power BI página 3\"}\n:::\n::: {.g-col-6}\n![Página 4 — Contratos, descuentos y adiciones](img/powerbi_p4.png){.lightbox fig-alt=\"Dashboard Power BI página 4\"}\n:::\n::: {.g-col-6}\n![Página 5 — Scorecard contratistas y modelo predictivo](img/powerbi_p5.png){.lightbox fig-alt=\"Dashboard Power BI página 5\"}\n:::\n:::\n\n### Python Dash\n\n::: {.grid}\n::: {.g-col-12}\n![Aplicación Dash — navegación lateral y cross-filtering interactivo](img/dash_p1.png){.lightbox fig-alt=\"Dashboard Dash página 1\"}\n:::\n::: {.g-col-6}\n![Dash — Curvas S con selector de proyecto](img/dash_p2.png){.lightbox fig-alt=\"Dashboard Dash página 2\"}\n:::\n::: {.g-col-6}\n![Dash — Modelo predictivo EAC y scorecard](img/dash_p5.png){.lightbox fig-alt=\"Dashboard Dash página 5\"}\n:::\n:::\n\n::: {.callout-note}\n**Power BI vs Python Dash:** Power BI ofrece cross-filtering nativo y publicación en la nube sin código. Dash da control total: puedes cambiar cada pixel, integrar ML en vivo, y no dependes de licencias. Para análisis exploratorio avanzado, Dash gana. Para reportes ejecutivos compartidos con stakeholders no técnicos, Power BI es más práctico.\n:::\n\n---\n\n## Scorecard de contratistas\n\n::: {#cell-fig-scorecard .cell execution_count=9}\n``` {.python .cell-code code-fold=\"true\"}\ncont = D[\"dim_contratista\"].copy()\ncpi_real = (\n    ultimo\n    .merge(D[\"dim_proyecto\"][[\"id_proyecto\",\"id_contratista_ppal\"]], on=\"id_proyecto\")\n    .groupby(\"id_contratista_ppal\")[\"CPI\"].mean()\n)\ncont[\"CPI_real\"] = cont[\"id_cont\"].map(cpi_real)\ncont = cont.sort_values(\"scorecard\", ascending=True)\n\nfig = go.Figure()\n\ncategorias = [\"calidad\", \"cumplimiento_plazo\", \"control_costo\"]\nlabels_cat = [\"Calidad\", \"Cumplimiento Plazo\", \"Control Costo\"]\ncolores_cat = [C[\"green\"], C[\"blue\"], C[\"gold\"]]\n\nfor cat, label, color in zip(categorias, labels_cat, colores_cat):\n    fig.add_trace(go.Bar(\n        y=cont[\"nombre\"],\n        x=cont[cat],\n        orientation=\"h\",\n        name=label,\n        marker_color=color,\n        opacity=0.8,\n        hovertemplate=f\"<b>%{{y}}</b><br>{label}: %{{x}}<extra></extra>\",\n    ))\n\n# Score total como texto\nfor _, row in cont.iterrows():\n    cpi_txt = f\"CPI {row['CPI_real']:.3f}\" if pd.notna(row[\"CPI_real\"]) else \"\"\n    fig.add_annotation(\n        y=row[\"nombre\"], x=105,\n        text=f\"<b>Score {row['scorecard']:.0f}</b>  {cpi_txt}\",\n        showarrow=False,\n        font=dict(size=10, color=C[\"navy\"]),\n        xanchor=\"left\",\n    )\n\nfig.update_layout(\n    barmode=\"group\",\n    height=280,\n    margin=dict(l=10, r=200, t=20, b=30),\n    paper_bgcolor=\"white\", plot_bgcolor=C[\"slate\"],\n    legend=dict(orientation=\"h\", y=1.08, font=dict(size=10)),\n    xaxis=dict(range=[0, 100], gridcolor=\"#eef2f7\", tickfont=dict(size=10)),\n    yaxis=dict(tickfont=dict(size=10)),\n    font=dict(family=\"Barlow, sans-serif\", size=11, color=C[\"muted\"]),\n)\nfig.show()\n```\n\n::: {#fig-scorecard .cell-output .cell-output-display}\n```{=html}\n<div>                            <div id=\"63e1f4ee-64b5-4a23-ac56-f32057ca9f0b\" class=\"plotly-graph-div\" style=\"height:280px; width:100%;\"></div>            <script type=\"text/javascript\">                require([\"plotly\"], function(Plotly) {                    window.PLOTLYENV=window.PLOTLYENV || {};                                    if (document.getElementById(\"63e1f4ee-64b5-4a23-ac56-f32057ca9f0b\")) {                    Plotly.newPlot(                        \"63e1f4ee-64b5-4a23-ac56-f32057ca9f0b\",                        [{\"hovertemplate\":\"\\u003cb\\u003e%{y}\\u003c\\u002fb\\u003e\\u003cbr\\u003eCalidad: %{x}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"marker\":{\"color\":\"#00b894\"},\"name\":\"Calidad\",\"opacity\":0.8,\"orientation\":\"h\",\"x\":[74,76,81,87,88,93,95],\"y\":[\"Concretos y Cimentaciones SAS\",\"Acabados Premium Colombia\",\"Tecnolog\\u00eda en Infraestructura\",\"Electrica Nacional SAS\",\"Obras y Vias del Norte S.A.S.\",\"Estructuras Modernas Ltda\",\"Hidrogeotecnia Consultores\"],\"type\":\"bar\"},{\"hovertemplate\":\"\\u003cb\\u003e%{y}\\u003c\\u002fb\\u003e\\u003cbr\\u003eCumplimiento Plazo: %{x}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"marker\":{\"color\":\"#3b82f6\"},\"name\":\"Cumplimiento Plazo\",\"opacity\":0.8,\"orientation\":\"h\",\"x\":[68,70,85,84,82,90,88],\"y\":[\"Concretos y Cimentaciones SAS\",\"Acabados Premium Colombia\",\"Tecnolog\\u00eda en Infraestructura\",\"Electrica Nacional SAS\",\"Obras y Vias del Norte S.A.S.\",\"Estructuras Modernas Ltda\",\"Hidrogeotecnia Consultores\"],\"type\":\"bar\"},{\"hovertemplate\":\"\\u003cb\\u003e%{y}\\u003c\\u002fb\\u003e\\u003cbr\\u003eControl Costo: %{x}\\u003cextra\\u003e\\u003c\\u002fextra\\u003e\",\"marker\":{\"color\":\"#c9a84c\"},\"name\":\"Control Costo\",\"opacity\":0.8,\"orientation\":\"h\",\"x\":[72,74,79,83,85,91,92],\"y\":[\"Concretos y Cimentaciones SAS\",\"Acabados Premium Colombia\",\"Tecnolog\\u00eda en Infraestructura\",\"Electrica Nacional SAS\",\"Obras y Vias del Norte S.A.S.\",\"Estructuras Modernas Ltda\",\"Hidrogeotecnia Consultores\"],\"type\":\"bar\"}],                        {\"template\":{\"data\":{\"histogram2dcontour\":[{\"type\":\"histogram2dcontour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"choropleth\":[{\"type\":\"choropleth\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"histogram2d\":[{\"type\":\"histogram2d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmap\":[{\"type\":\"heatmap\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"heatmapgl\":[{\"type\":\"heatmapgl\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"contourcarpet\":[{\"type\":\"contourcarpet\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"contour\":[{\"type\":\"contour\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"surface\":[{\"type\":\"surface\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]}],\"mesh3d\":[{\"type\":\"mesh3d\",\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"parcoords\":[{\"type\":\"parcoords\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolargl\":[{\"type\":\"scatterpolargl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"scattergeo\":[{\"type\":\"scattergeo\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterpolar\":[{\"type\":\"scatterpolar\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"scattergl\":[{\"type\":\"scattergl\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatter3d\":[{\"type\":\"scatter3d\",\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattermapbox\":[{\"type\":\"scattermapbox\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scatterternary\":[{\"type\":\"scatterternary\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"scattercarpet\":[{\"type\":\"scattercarpet\",\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}}}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"minorgridcolor\":\"white\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}],\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"#E5ECF6\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}]},\"layout\":{\"autotypenumbers\":\"strict\",\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"hovermode\":\"closest\",\"hoverlabel\":{\"align\":\"left\"},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#E5ECF6\",\"polar\":{\"bgcolor\":\"#E5ECF6\",\"angularaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"radialaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"ternary\":{\"bgcolor\":\"#E5ECF6\",\"aaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"},\"caxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\"}},\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]]},\"xaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"yaxis\":{\"gridcolor\":\"white\",\"linecolor\":\"white\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"white\",\"automargin\":true,\"zerolinewidth\":2},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"yaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2},\"zaxis\":{\"backgroundcolor\":\"#E5ECF6\",\"gridcolor\":\"white\",\"linecolor\":\"white\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"white\",\"gridwidth\":2}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"geo\":{\"bgcolor\":\"white\",\"landcolor\":\"#E5ECF6\",\"subunitcolor\":\"white\",\"showland\":true,\"showlakes\":true,\"lakecolor\":\"white\"},\"title\":{\"x\":0.05},\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30}}},\"annotations\":[{\"font\":{\"color\":\"#0f1f3d\",\"size\":10},\"showarrow\":false,\"text\":\"\\u003cb\\u003eScore 71\\u003c\\u002fb\\u003e  \",\"x\":105,\"xanchor\":\"left\",\"y\":\"Concretos y Cimentaciones SAS\"},{\"font\":{\"color\":\"#0f1f3d\",\"size\":10},\"showarrow\":false,\"text\":\"\\u003cb\\u003eScore 73\\u003c\\u002fb\\u003e  \",\"x\":105,\"xanchor\":\"left\",\"y\":\"Acabados Premium Colombia\"},{\"font\":{\"color\":\"#0f1f3d\",\"size\":10},\"showarrow\":false,\"text\":\"\\u003cb\\u003eScore 82\\u003c\\u002fb\\u003e  CPI 0.877\",\"x\":105,\"xanchor\":\"left\",\"y\":\"Tecnolog\\u00eda en Infraestructura\"},{\"font\":{\"color\":\"#0f1f3d\",\"size\":10},\"showarrow\":false,\"text\":\"\\u003cb\\u003eScore 85\\u003c\\u002fb\\u003e  \",\"x\":105,\"xanchor\":\"left\",\"y\":\"Electrica Nacional SAS\"},{\"font\":{\"color\":\"#0f1f3d\",\"size\":10},\"showarrow\":false,\"text\":\"\\u003cb\\u003eScore 85\\u003c\\u002fb\\u003e  CPI 0.865\",\"x\":105,\"xanchor\":\"left\",\"y\":\"Obras y Vias del Norte S.A.S.\"},{\"font\":{\"color\":\"#0f1f3d\",\"size\":10},\"showarrow\":false,\"text\":\"\\u003cb\\u003eScore 92\\u003c\\u002fb\\u003e  CPI 0.960\",\"x\":105,\"xanchor\":\"left\",\"y\":\"Estructuras Modernas Ltda\"},{\"font\":{\"color\":\"#0f1f3d\",\"size\":10},\"showarrow\":false,\"text\":\"\\u003cb\\u003eScore 92\\u003c\\u002fb\\u003e  CPI 0.978\",\"x\":105,\"xanchor\":\"left\",\"y\":\"Hidrogeotecnia Consultores\"}],\"margin\":{\"l\":10,\"r\":200,\"t\":20,\"b\":30},\"legend\":{\"font\":{\"size\":10},\"orientation\":\"h\",\"y\":1.08},\"xaxis\":{\"tickfont\":{\"size\":10},\"range\":[0,100],\"gridcolor\":\"#eef2f7\"},\"yaxis\":{\"tickfont\":{\"size\":10}},\"font\":{\"family\":\"Barlow, sans-serif\",\"size\":11,\"color\":\"#8899aa\"},\"barmode\":\"group\",\"height\":280,\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#f0f4f8\"},                        {\"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('63e1f4ee-64b5-4a23-ac56-f32057ca9f0b');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };                });            </script>        </div>\n```\n\nScorecard de contratistas — calidad, plazo, costo y CPI real\n:::\n:::\n\n\n**Hallazgo:** los contratistas con score ≥ 90 (ponderación: calidad 40%, plazo 35%, costo 25%) muestran un CPI real superior a 0.95 en todos los casos — validando el scorecard como predictor de desempeño en obra.\n\n---\n\n## Estructura del modelo de datos\n\nEl modelo sigue un **esquema estrella** estándar de data warehouse, optimizado para Power BI y compatible con cualquier herramienta BI:\n\n```\n                    ┌─────────────────┐\n                    │   dim_tiempo    │\n                    │  id_tiempo (PK) │\n                    └────────┬────────┘\n                             │\n┌──────────────┐    ┌────────▼────────┐    ┌──────────────────┐\n│ dim_proyecto │◄───┤ fact_avance_obra│    │  dim_contratista │\n│ id_proyecto  │    │ id_proyecto (FK)│◄───┤  id_cont (PK)    │\n│ nombre       │    │ id_tiempo  (FK) │    └──────────────────┘\n│ tipo         │    │ PV · EV · AC    │\n│ presupuesto  │    │ CPI · SPI       │\n└──────┬───────┘    └─────────────────┘\n       │\n       ├──► fact_contratos\n       ├──► fact_adiciones\n       └──► fact_presupuesto_apu ──► dim_capitulo\n```\n\n---\n\n## Código fuente\n\nEl proyecto está organizado en dos archivos principales:\n\n| Archivo | Descripción | Líneas |\n|---|---|---|\n| `construccion_analitica.py` | Genera los 11 CSV con datos sintéticos realistas | ~780 |\n| `dashboard_construccion.py` | App Dash completa con 5 páginas y cross-filtering | ~1200 |\n\n::: {#snippet-evm .cell execution_count=10}\n``` {.python .cell-code code-fold=\"false\" code-summary=\"Ejemplo: cálculo EVM y generación de curva S\"}\n# Ejemplo simplificado del patrón usado en construccion_analitica.py\n\ndef factor_mes(mes_rel, plazo, rc_final):\n    \"\"\"\n    Interpola CPI de 1.0 a rc_final usando sigmoide.\n    Inflexión en el 35% del plazo — comportamiento real de obra.\n    \"\"\"\n    import math\n    x = (mes_rel / plazo - 0.35) * 12\n    s = 1 / (1 + math.exp(-x))\n    return 1.0 + (rc_final - 1.0) * s\n\ndef curva_s_sigmoide(mes, plazo):\n    \"\"\"\n    Avance planeado acumulado — forma S matemáticamente correcta.\n    Evita valores negativos en los primeros meses.\n    \"\"\"\n    import math\n    def s(t): return 1 / (1 + math.exp(-10 * (t/plazo - 0.5)))\n    s0, s1 = s(0), s(plazo)\n    return (s(mes) - s0) / (s1 - s0)\n\n# Ejemplo de uso\nplazo = 12\nfor mes in [1, 4, 6, 9, 12]:\n    pv_pct  = curva_s_sigmoide(mes, plazo) * 100\n    cpi_sim = 1 / factor_mes(mes, plazo, rc_final=1.10)\n    print(f\"Mes {mes:2d}: PV acumulado = {pv_pct:5.1f}%  |  CPI simulado = {cpi_sim:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMes  1: PV acumulado =   0.9%  |  CPI simulado = 0.996\nMes  4: PV acumulado =  15.4%  |  CPI simulado = 0.957\nMes  6: PV acumulado =  50.0%  |  CPI simulado = 0.921\nMes  9: PV acumulado =  93.0%  |  CPI simulado = 0.910\nMes 12: PV acumulado = 100.0%  |  CPI simulado = 0.909\n```\n:::\n:::\n\n\n---\n\n## Conclusiones\n\nA partir del análisis del portafolio de **$50.88B COP** con corte a septiembre de 2024:\n\n1. **El portafolio presenta sobrecosto generalizado** — CPI consolidado de 0\\.923, con proyección de cierre en $55\\.141 B COP (+8\\.4% sobre el BAC).\n\n2. **PRY003 (Puente Magdalena) es el proyecto de mayor riesgo** — CPI 0.850 en umbral crítico, desviación estimada al cierre del +18.9%. Requiere plan de contingencia inmediato.\n\n3. **Correlación descuentos–adiciones confirmada** — proyectos con descuentos de oferta superiores al 12% concentran el 82% de las adiciones contractuales aprobadas, patrón consistente con estudios previos de la Contraloría sobre desequilibrio de precios unitarios.\n\n4. **El modelo predictivo es confiable** — R² promedio de 0\\.949 en los 8 proyectos, validado con separación temporal train/test.\n\n5. **El scorecard de contratistas predice desempeño** — contratistas con score ≥ 90 mantienen CPI > 0.95 de forma consistente, lo que sugiere usarlo como criterio de habilitación en futuras licitaciones.\n\n---\n\n## Herramientas y referencias\n\n**Stack utilizado:**\n`Python 3.11` · `pandas` · `plotly` · `Dash` · `numpy` · `Power BI Desktop` · `Quarto`\n\n**Referencias sectoriales:**\n- INVIAS — *Manual de Interventoría y Supervisión de Contratos* (2022)\n- Camacol — *Costos de Construcción por M²* (2024)\n- PMI — *Practice Standard for Earned Value Management*, 3rd ed.\n- DANE — *Índice de Costos de la Construcción de Vivienda* (ICCV)\n\n**Código fuente:**\n[github.com/tu-usuario/construccion-analitica](https://github.com/tu-usuario/construccion-analitica) <!-- reemplaza con tu URL -->\n\n",
    "supporting": [
      "construccion_analitica_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n<script type=\"text/javascript\">\nwindow.PlotlyConfig = {MathJaxConfig: 'local'};\nif (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}\nif (typeof require !== 'undefined') {\nrequire.undef(\"plotly\");\nrequirejs.config({\n    paths: {\n        'plotly': ['https://cdn.plot.ly/plotly-2.35.2.min']\n    }\n});\nrequire(['plotly'], function(Plotly) {\n    window._Plotly = Plotly;\n});\n}\n</script>\n\n"
      ]
    }
  }
}