name: Render Quarto Site

on:
  push:
    branches: [main]  # Cambia a "master" si tu rama principal es diferente
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Ajusta si necesitas otra versión

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbformat numpy pandas matplotlib seaborn scipy scikit-learn scikit-posthocs statsmodels plotly

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.0'  # Ajusta si necesitas otra versión

      - name: Install R dependencies
        run: |
          R -e "install.packages(c('knitr', 'rmarkdown', 'ggplot2', 'dplyr', 'tidyr', 'readr', 'lubridate', 'stringr', 'plotly', 'data.table', 'caret'), repos='https://cloud.r-project.org/')"

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      #- name: Install Quarto extensions
        #run: |
          #quarto add mcanouil/quarto-iconify

      - name: Render Quarto Site
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site