name: Render Quarto Site

on:
  push:
    branches: [main]  # Cambia a "master" si tu rama principal es diferente
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configurar caché para Python
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('dependencies/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dependencies/requirements.txt

      - name: Cache R dependencies
        uses: actions/cache@v3
        with:
          path: /usr/local/lib/R/site-library
          key: ${{ runner.os }}-r-${{ hashFiles('dependencies/install.R') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.0'

      - name: Check R library paths
        run: |
          Rscript -e "print(.libPaths())"

      - name: Install R dependencies
        run: |
          echo "Inicio: $(date)"
          sudo Rscript dependencies/install.R
          echo "Fin: $(date)"

      # Configurar caché para Quarto
      - name: Cache Quarto and Extensions
        uses: actions/cache@v3
        with:
          path: ~/.quarto
          #key: ${{ runner.os }}-quarto-${{ hashFiles('.github/workflows/quarto-render.yml') }}
          key: ${{ runner.os }}-quarto-${{ hashFiles('dependencies/quarto-extensions.txt') }}
          restore-keys: |
            ${{ runner.os }}-quarto-

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Quarto Extensions
        run: |
          while IFS= read -r ext; do quarto add "$ext"; done < dependencies/quarto-extensions.txt

      - name: Render Quarto Site
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site